#!/bin/bash

#####################################################
#													#
# Succynct  |	Author  :   Alex Fontaine-Bolanos	#
#           |   Created :   17/8/2022               #
#													#
#####################################################

# Checks to see if succynct-config exist
configExist(){
    if ( test -e ~/.local/share/succynct/succynct-config );then
        run
    else
        config
    fi
}

# Gathers the config data from succynct-config. Then executes the interval time. When the time is up, it compares the destination file/folder to that of the source. Then makes a copy.
run(){
    srcLine=$(($(sed -n "/Source/=" succynct-config)+1))
    destLine=$(($(sed -n "/Destination/=" succynct-config)+1))
    selectLine=$(($(sed -n "/Selection/=" succynct-config)+1))
    iLine=$(($(sed -n "/Intervals/=" succynct-config)+1))
    dateLine=$(($(sed -n "/Date/=" succynct-config)+1))
    src=$(sed -n "$srcLine p" succynct-config)
    dest=$(sed -n "$destLine p" succynct-config)
    s=$(sed -n "$selectLine p" succynct-config)
    i=$(sed -n "$iLine p" succynct-config)
    d=$(sed -n "$dateLine p" succynct-config)
    ti=$(($(date -d @$d +%s)-$(date +%s)))	# ti = Time interval.

    mtime(){
        stat -c %Y $1
    }

    fileSync(){
        destf=$dest/$(basename $src)    # Synced file/folder
        smtime=$(mtime $src)            # Last modified source time
        bmtime=$(mtime $destf)          # Last modified scynced time

        #Makes copy if none exist.
        if ( test ! -e $destf );then
            cp -a $src $dest
            chmod a-w $destf
            destf=$dest/$(basename $src)
            bmtime=$(mtime $destf)
        fi
        #Restores source file/folder if missing
        if ( test ! -e $src );then
            cp -a $destf $(dirname $src)
            chmod u+w $src
        fi
        #Checks modified time differences, then copy if there is any.
        if [ $smtime -gt $bmtime ];then
            cp -a $src $dest
            chmod a-w $destf
        fi
    }

    echo "Source: $src"
    echo "Destination: $dest"
    echo "Selection: $s"
    echo "Interval: $i"
    if [[ $s = "i" ]];then
        echo "Synchronisation at: $(date -d "+$i sec")"
    else
        echo "Synchronisation at: $(date -d @$d)"
    fi

    # Checks if synchronisation time has passed
    while true; do
        case $s in
            i)  fileSync
                echo "Synched at $(date)"
                echo "Next synchronisation at $(date -d "+$i sec")"
                sleep $i
                ;;
            d)	if [ $(date +%s) -ge $d ];then
                    fileSync
                    newDate=$(($(date -d "today $i" +%s)+(24*60*60))) # New date = +24h
                    sed -i "s/$d/$newDate/" succynct-config
                    d=$newDate
                    echo "Synched at $(date)"
                    echo "Next synchronisation at $(date -d @$d)"
                fi
                sleep $ti
                ti=$(($(date -d @$d +%s)-$(date +%s)))	# New interval updated.
                ;;
            w)	if [ $(date +%s) -ge $d ];then
                    fileSync
                    newDate=$(($(date -d "today $i" +%s)+(7*24*60*60))) # New date = +7 days
                    sed -i "s/$d/$newDate/" succynct-config
                    d=$newDate
                    echo "Synched at $(date)"
                    echo "Next synchronisation at $(date -d @$d)"
                fi
                sleep $ti
                ti=$(($(date -d @$d +%s)-$(date +%s)))
                ;;
            m)	if [ $(date +%s) -ge $d ];then
                    fileSync
                    newDate=$(date -d +month +%s) # New date = +1 month
                    sed -i "s/$d/$newDate/" succynct-config
                    d=$newDate
                    echo "Synched at $(date)"
                    echo "Next synchronisation at $(date -d @$d)"
                fi
                sleep $ti
                ti=$(($(date -d @$d +%s)-$(date +%s)))
                ;;
            y)	if [ $(date +%s) -ge $d ];then
                    fileSync
                    newDate=$(date -d +year +%s) # New date = +1 month
                    sed -i "s/$d/$newDate/" succynct-config
                    d=$newDate
                    echo "Synched at $(date)"
                    echo "Next synchronisation at $(date -d @$d)"
                fi
                sleep $ti
                ti=$(($(date -d @$d +%s)-$(date +%s)))
                ;;
        esac
    done
}

# Syncing configuration
config(){
    while true; do
        read -p "Source file/folder: " src
        if ( test ! -e $src ) || [ -z "$src" ]; then 			#If file/folder does not exist or empty(0)
            read -p $"File or Directory does not exit. Press ENTER to try again"
        else
            break
        fi
    done

    while true; do 								#If file/folder does not exist or empty(0)
        read -p "Destination folder: " dest
        if ( test ! -d $dest ) || [ -z "$dest" ]; then 			#If file/folder does not exist or empty(0)
            read -p $"Destination Directory does not exist. Press ENTER to try again."
        else
            break
        fi
    done

    while true ;do
        read -p "How do you want the source be synced?

            (i)	Intervals
            (d)	Daily
            (w)	Weekly
            (m)	Monthly	(Not implemented)
            (y)	Yearly	(Not Implemented)

            Select one: " s				# s = select

        case $s in
            i)	read -p "Choose an interval (min): " t
                break
                ;;
            d)	read -p "Choose time of day (24) (HH): " t
                break
                ;;
            w)	read -p "Starting date (YYYYMMDD) (DD recommended max at 28): " d
                read -p "Choose time of day (24) (HH): " t
                break
                ;;
            m)	read -p "Starting date (YYYYMMDD) (DD recommended max at 28): " d
                read -p "Choose time (24) (HH): " t
                break
                ;;
            y)	read -p "Starting date (YYYYMMDD): " d
                read -p "Choose time (24) (HH): " t
                break
                ;;
            *)	"Invalid input."
                ;;
        esac
    done

    echo "# Source" > succynct-config
    echo "# Destination" >> succynct-config
    echo "# Selection" >> succynct-config
    echo "# Intervals" >> succynct-config
    echo "# Date" >> succynct-config

    line=$(sed -n "/Source/=" succynct-config)
    sed -i "$line a$src" succynct-config

    line=$(sed -n "/Destination/=" succynct-config)
    sed -i "$line a$dest" succynct-config

    case $s in
        i)	t=$(($t*60))
            line=$(sed -n "/Selection/=" succynct-config)
            sed -i "$line a$s" succynct-config
            line=$(sed -n "/Intervals/=" succynct-config)
            sed -i "$line a$t" succynct-config
            ;;
        d)	d=$(date -d "today $t" +%s)
            line=$(sed -n "/Selection/=" succynct-config)
            sed -i "$line a$s" succynct-config
            line=$(sed -n "/Intervals/=" succynct-config)
            sed -i "$line a$t" succynct-config
            line=$(sed -n "/Date/=" succynct-config)
            sed -i "$line a$d" succynct-config
            ;;
        w)	d=$(date -d $d +%s)
            line=$(sed -n "/Selection/=" succynct-config)
            sed -i "$line a$s" succynct-config
            line=$(sed -n "/Intervals/=" succynct-config)
            sed -i "$line a$t" succynct-config
            line=$(sed -n "/Date/=" succynct-config)
            sed -i "$line a$d" succynct-config
            ;;
        m)	d=$(date -d $d +%s)
            line=$(sed -n "/Selection/=" succynct-config)
            sed -i "$line a$s" succynct-config
            line=$(sed -n "/Intervals/=" succynct-config)
            sed -i "$line a$t" succynct-config
            line=$(sed -n "/Date/=" succynct-config)
            sed -i "$line a$d" succynct-config
            ;;
        y)	d=$(date -d $d +%s)
            line=$(sed -n "/Selection/=" succynct-config)
            sed -i "$line a$s" succynct-config
            line=$(sed -n "/Intervals/=" succynct-config)
            sed -i "$line a$t" succynct-config
            line=$(sed -n "/Date/=" succynct-config)
            sed -i "$line a$d" succynct-config
            ;;
    esac

    if ( test ! -e ~/.local/share/succynct ); then
        mkdir ~/.local/share/succynct
        mv succynct-config ~/.local/share/succynct/
        echo "[Desktop Entry]
        Type=Application
        Name=succynct
        Exec=~/.local/share/succynct/succynct
        Icon=utilities-terminal
        " >> ~/.config/autostart/succynct.desktop
        mv succynct ~/.local/share/succynct/
    fi

    run
}

if [[ $1 = "-m" ]];then
    config
else
    configExist
fi
